/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayPlayerRouteImport } from './routes/play-player'
import { Route as PlayCpuRouteImport } from './routes/play-cpu'
import { Route as IndexRouteImport } from './routes/index'

const PlayPlayerRoute = PlayPlayerRouteImport.update({
  id: '/play-player',
  path: '/play-player',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCpuRoute = PlayCpuRouteImport.update({
  id: '/play-cpu',
  path: '/play-cpu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play-cpu': typeof PlayCpuRoute
  '/play-player': typeof PlayPlayerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play-cpu': typeof PlayCpuRoute
  '/play-player': typeof PlayPlayerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play-cpu': typeof PlayCpuRoute
  '/play-player': typeof PlayPlayerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/play-cpu' | '/play-player'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/play-cpu' | '/play-player'
  id: '__root__' | '/' | '/play-cpu' | '/play-player'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayCpuRoute: typeof PlayCpuRoute
  PlayPlayerRoute: typeof PlayPlayerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play-player': {
      id: '/play-player'
      path: '/play-player'
      fullPath: '/play-player'
      preLoaderRoute: typeof PlayPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-cpu': {
      id: '/play-cpu'
      path: '/play-cpu'
      fullPath: '/play-cpu'
      preLoaderRoute: typeof PlayCpuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayCpuRoute: PlayCpuRoute,
  PlayPlayerRoute: PlayPlayerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
